# Generated by Django 4.1.3 on 2023-01-16 20:07

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data:')),
                ('horario', models.TimeField(verbose_name='Horário:')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome:')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF:')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Gênero:')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone:')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Especialidade:')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome:')),
                ('crm', models.CharField(max_length=20, verbose_name='CRM:')),
                ('email', models.EmailField(max_length=30, verbose_name='E-mail:')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone:')),
                ('especialidade_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.especialidade', verbose_name='Especialidade:')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.agenda', verbose_name='Data e Horário:')),
                ('nome_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico', verbose_name='Nome do Médico:')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='nome_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico', verbose_name='Nome do Médico:'),
        ),
    ]
